### ISSUE TITLE
IR Receiver not working

### ISSUE THREAD

**Issue by pholcroft** [colortiger/anymotuino#1]
No matter what I do I can't seem to get the IR Receiver to work. Everything else seems to work fine. can you recommend a way to debug this?

**Comment by stumpja** [comment]
Pholcroft,

I'm happy to hear you have basically gotten your anymotuino to work. I have recently built one, but I an unable to connect to the iOS anymote app. I assume you are using iOS, or do you have an android phone that doesn't have an ir blaster? An information would be great. Thanks in advance for your time.

Josh

**Comment by pholcroft** [comment]
Hi Josh,

I have an android phone (One Plus One) which doesn't have an IR blaster and I am using the Anymote App. It was a while ago now, but I can't remember have any problems getting it to work, did you add the test LED? I did email the developers of the Anymote app about some issues with the app and bluetooth, they responded with an updated version which fixed my issues. That is another route you could try.

**Comment by stumpja** [comment]
Pholcroft,

I really appreciate the reply. I sent an email to them yesterday, but haven't heard back yet. I will say, I emailed them in the past and they were pretty responsive. Maybe I can borrow an android phone and rule out the hardware. Whats interesting, is that it just won't recognize the device at all, alluding to it not seeing the HM-10. I can connect to the HM-10 through another app (I.E. LIGHTBLUE). This leads me to thinking if I need to configure the HM-10 in some way for it to work properly with the app. Did you have to change the name of the HM-10 for the app to recognize it?

Anyways, thanks again for the quick response. So were you able to get the IR reciever to work properly with the app update?

(EDIT: Also, I didn't add the test LED, but I measured it with a DMM. It is changing from 0 to 3.3V, basically meaning it isn't connected. )

Thanks,

Josh

**Comment by pholcroft** [comment]
The hm-10 is really weird. I can't see it in my Bluetooth connection settings, but anymote connects to it somehow? I bought two of them and tried to update the second one with the latest firmware, but I couldn't get the serial connection to work to talk to it. The one I used in the device I used straight out of the packet. I didn't put too much effort into updating the second one though as I had it working with the first one. I think maybe I bought a hm-10 clone.

The issue with the app wasn't a major one. It was just when you sent the first command when the Bluetooth wasn't connected it wouldn't wait for the connection to finish before sending the command, but that was only an issue the first time I used it. It didn't stop me using it.

Really we need a version of this which uses the esp8266 instead of hm-10 Bluetooth, but I don't have the time to learn this at the moment to do it myself.

**Comment by stumpja** [comment]
I'm starting to get the feeling it just isn't supported in the iOS version of the app. I have a couple other HM-10's I can try, but I don't have a good feeling about it. The iOS version of the app is free, presumably due to the fact that no iPhones have IR blasters, so they are likely forcing you to buy their anymote in order to use the app. I may end up buying the anymote, I just wanted to at least test the app and usability with the anymotuino first before I made the plunge.

Being able to use the ESP instead of the HM-10 would be great. I'm definitely more comfortable with wifi than bluetooth. The code for the arduino would be fairly straight forward, however the code for the android/ios app isn't available, so it would be impossible to implement without writing your own standalone application. [EDIT: so I just went out and looked, and it seems the app does support wifi enabled arduino's, at least on iOS. This may only be in the beta, which unfortunately, I can't download. I will try to send out some emails to colortiger by the end of the week with additional questions about this and other items. If I can get this working with the ESP8266, I will let you know.]

Again, thanks for all your help!

Josh

**Comment by pholcroft** [comment]
The Anymote supports Global Cache iTach WiFi to IR devices. The spec is here: 
http://www.globalcache.com/products/itach/wf2irspecs/
(the help in Anymote it says it works with iPhone's).
These devices aren't cheap.

The information is available, it just needs to be programmed using an arduino, or it's possible the esp8266 might even be able to handle it itself.

**Comment by stumpja** [comment]
Very interesting. This would be a great project to work on. Provided I get some time I may dig deeper into this.

I did want to say. Color Tiger did get back with me this morning. The following response was given:

> _when you launch the iOS app and get to the "searching for your AnyMotes stage", after 8 seconds_
> _a message will appear. Right at the bottom of the screen, there will be an "I already have an_
> _AnyMote Home" text: long-press that, and you're into the "Anymotuino discovery mode"._

This has fixed my connection issue. I will begin testing the other features out. Thanks for all your feedback. it has been much appreciated. If I ever get around to working with the ESP8266 and Anymote I will post my results here.

Thanks again,

Josh

**Comment by pholcroft** [comment]
Glad to hear you got it working and that Anymote were helpful.

The problem with Bluetooth is that it takes time to connect the first time you use it. This happens frequently when you walk out of Bluetooth range. Although the individual commands wait for connection, the macro's don't. Everytime I use the app I have to press OK, wait for that to show up on the screen, then press my macro button. WiFi would be a much better solution as connection shouldn't be an issue.

Please let me know if the recording feature works for you.

**Comment by davcenmt2** [comment]
@pholcroft @stumpja do either of you still use your anymotuino. I'm having trouble getting anymote app to recognize the hm-10. I have a feeling its may not be compatible with newest version of anymote app as I was able to get really old version to recognize it but nothing worked. 

I've emailed ColorTiger to see what they have to say, but wanted to see if you guys every had any trouble as the app updated?

**Comment by stumpja** [comment]
@davcenmt2
I was able to connect with an older version and get commands to work properly, however, I had to shut down the app every time and reconnect when I wanted to use it again. Due to this, I stopped using it.

I still have the hardware laying around in pieces at the moment. I would love to get it going, just figured it might be easier to use another app to get it to do what I really want. I really like Bluetuino, it isn't perfect, but it works and is customizable. The user interface isn't the greatest, but it should work, will require some more in depth programming and app design though. Check it out. I haven't had time yet to really get this going, just verifies basic functionality. One other thought, just recently backed a project of Indiegogo called riimo. This could solve my problems, assuming they deliver. Check that out as well. They have partnered with arrow, a highly respected distributer, so that is a good sign.

If you do hear back from color tiger, please post the response here. I like the app, and if it would work, I'd love to use it. Thanks!

**Comment by davcenmt2** [comment]
@stumpja 
Thanks for the fast reply. I'll definitely let you know what I hear from them. I'd love if I could get it working! Coming from an S5 with IR blaster built in, that's one thing I miss with my new phone.

I'll have to check out the Bluetuino alternative. thanks for the suggestions.

**Comment by davcenmt2** [comment]
@stumpja 
looks like anymotuino is no more. Finally got a reply from Colortiger -

"am sorry for this, we'll have to remove anymotuino from Git as it interferes with AnyMote. (and we had to remove it from our app too in the last updates)
It makes the discovery of AnyMote devices very slow as we have to look out for anymotuino devices."
